-- Execute este SQL no Supabase > SQL Editor

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null check (char_length(full_name) >= 3),
  phone text not null,
  email text not null,
  consent boolean not null default false,
  event_slug text not null default 'escola-mocos-profetas-07-08-11'
);

-- Evita inscrição duplicada por e-mail ou telefone no mesmo evento
create unique index if not exists registrations_event_email_unique
  on public.registrations (event_slug, lower(email));

create unique index if not exists registrations_event_phone_unique
  on public.registrations (event_slug, phone);

alter table public.registrations enable row level security;

-- Permite ao site público SOMENTE inserir novas inscrições.
drop policy if exists "public can insert registrations" on public.registrations;
create policy "public can insert registrations"
on public.registrations
for insert
to anon
with check (
  consent = true
  and char_length(full_name) >= 3
  and char_length(phone) >= 10
  and char_length(email) >= 5
);

-- Não crie policy de SELECT para anon.
-- Assim os visitantes não conseguem ler a lista de inscritos.
-- Para ver quantidade e dados, use o painel do Supabase autenticado.

-- Consulta para contar inscritos no painel:
-- select count(*) as total_inscritos
-- from public.registrations
-- where event_slug = 'escola-mocos-profetas-07-08-11';

-- Consulta para exportar a lista:
-- select created_at, full_name, phone, email
-- from public.registrations
-- where event_slug = 'escola-mocos-profetas-07-08-11'
-- order by created_at desc;
